[versions]
agp = "8.8.1"  # Android Gradle Plugin
gson = "2.10.1"
hiltAndroid = "2.55"  # Обновленная версия Hilt
hiltNavigationCompose = "1.2.0"  # Обновленная версия Hilt Navigation Compose
kotlin = "2.1.0"  # Kotlin
coreKtx = "1.15.0"  # AndroidX Core KTX
junit = "4.13.2"  # JUnit
junitVersion = "1.2.1"  # AndroidX JUnit
espressoCore = "3.6.1"  # Espresso Core
appcompat = "1.7.0"  # AppCompat
ktorClientCore = "3.1.0"  # Ktor Client Core
ktorUtils = "3.1.0"  # Ktor Utils
material = "1.12.0"  # Material Components
constraintlayout = "2.2.0"  # ConstraintLayout
lifecycleLivedataKtx = "2.8.7"  # Lifecycle LiveData KTX
lifecycleViewmodelKtx = "2.8.7"  # Lifecycle ViewModel KTX
navigationFragmentKtx = "2.8.7"  # Navigation Fragment KTX
navigationUiKtx = "2.8.7"  # Navigation UI KTX
annotation = "1.9.1"  # AndroidX Annotation
activity = "1.10.0"  # AndroidX Activity
postgrestKt = "3.1.1"  # Supabase PostgREST
storageKt = "3.1.1"  # Supabase Storage

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "postgrestKt" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktorUtils" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
storage-kt = { module = "io.github.jan-tennert.supabase:storage-kt", version.ref = "storageKt" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "postgrestKt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }